version: '3.8'

services:
  frontend: 
    build: .
    ports:
      - "19000:19000"
    volumes:
      - ./app/assets:/srv/app/assets
      - ./app/redux:/srv/app/redux
      - ./app/src:/srv/app/src
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.100.17
      - REACT_APP_BACKEND_URL=https://192.168.100.17:8080
      # - EXPO_USER=
      # - EXPO_PASSWORD=