version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8080"
    # volumes:
    #   - "./app:/app"
  # db:
  #   image: postgres:12.1-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres