# Generated by Django 4.2.7 on 2024-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
