# Generated by Django 4.2.7 on 2024-01-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_neighborhood_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='communities.bankaccount')),
            ],
        ),
    ]
