# Generated by Django 4.2.7 on 2024-01-09 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
