# Generated by Django 4.2.7 on 2024-01-09 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_rename_archivo_pdf_agreement_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
