# Generated by Django 4.2.7 on 2024-01-09 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_agreement_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
