# Generated by Django 4.2.7 on 2024-01-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, default=None, upload_to='profile/'),
        ),
    ]
