# Generated by Django 4.2.7 on 2024-01-08 05:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(max_length=2000, upload_to='profile/', validators=[accounts.models.validate_file_size]),
        ),
    ]
