# Generated by Django 4.2.7 on 2024-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
